spring.datasource.url=jdbc:postgresql://localhost:5432/travimate
spring.datasource.username=fajar
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

openapi.dev-url=http://34.124.247.20:8080
openapi.prod-url=https://travimate.com

#logging.level.net.sf.jasperreports=DEBUG

travimate.app.jwtSecret = "travimate-secret-key"
