#spring.datasource.url=jdbc:postgresql://localhost:5432/travmatefinal
#spring.datasource.username=postgres
#spring.datasource.password=123
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto = update
#
#gcloud auth application-default login --no-launch-browser
#
#4/0AfJohXmpdu2eW4ZOAOcdkiqTb74JhvdpHM6S0jZRSqc7sjCQaIX3RYk2NB3x46PRDpA_iQ

spring.cloud.gcp.sql.database-name=synergy-database
spring.cloud.gcp.sql.instance-connection-name=synrgy-challenge:asia-southeast1:synergy-database
spring.cloud.gcp.project-id=synrgy-challenge
spring.cloud.gcp.credentials.location=classpath:synrgy-challenge-034251c03b9a.json

# Leave empty for root, uncomment and fill out if you specified a user
#spring.datasource.username=

# Uncomment if root password is specified
spring.datasource.password=travimateDB

spring.sql.init.mode=always
server.error.include-message=always
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
